language: java

jdk:
  - openjdk14

env:
  global:
    - CODECOV_TOKEN="ecde83b7-6122-4f84-907f-1266ce0e4fe1"

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - ronios@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always
