language: java

jdk:
  - openjdk14

env:
  global:
    - CODECOV_TOKEN="d13c64ca-0b76-44ef-8dcf-08b1d8418290"

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - ronios@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always
